# Generated by Django 5.1.2 on 2025-02-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='employee',
            new_name='creator',
        ),
    ]
