# Generated by Django 5.1.2 on 2025-02-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_drink_last_updated_alter_drink_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='creator',
            new_name='user',
        ),
    ]
