# Generated by Django 5.1.2 on 2025-02-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_rename_creator_drink_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='user',
            new_name='creator',
        ),
    ]
