# Generated by Django 5.1.2 on 2025-02-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_rename_user_drink_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
