# Generated by Django 5.1.2 on 2025-02-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0006_alter_drink_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
