# Generated by Django 5.1.2 on 2025-02-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0009_category_alter_drink_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
