# Generated by Django 5.1.2 on 2025-02-14 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0010_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
