# Generated by Django 5.1.2 on 2025-02-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0012_edithistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='creator',
            new_name='employee',
        ),
    ]
