# Generated by Django 5.1.2 on 2025-02-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0013_rename_creator_drink_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='edithistory',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
